[package]
name = "example-json-codec"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "json-codec-server"
path = "src/server.rs"

[[bin]]
name = "json-codec-client"
path = "src/client.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
tonic = { path = "../../tonic" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1"

[build-dependencies]
tonic-build = { path = "../../tonic-build" }
