[package]
name = "example-attr"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11"
tonic = { path = "../../tonic" }

[build-dependencies]
tonic-build = { path = "../../tonic-build" }
