[package]
name = "example-autoreload"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "autoreload-server"
path = "src/server.rs"

[dependencies]
tokio-stream = { version = "0.1", features = ["net"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
tonic = { path = "../../tonic" }
listenfd = "1.0"

[build-dependencies]
tonic-build = { path = "../../tonic-build" }
