[package]
name = "example-tower"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "tower-server"
path = "src/server.rs"

[[bin]]
name = "tower-client"
path = "src/client.rs"

[dependencies]
futures = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
tonic = { path = "../../tonic" }
hyper = { version = "0.14" }
tower = "0.4"
http = "0.2"

[build-dependencies]
tonic-build = { path = "../../tonic-build" }
