[package]
name = "web-interop"
version = "0.1.0"
authors = ["Juan Alvarez <j@yabit.io>"]
publish = false
edition = "2018"

[dependencies]
interop = { path = "../../interop" }
tonic = { path = "../../tonic" }
tonic-web = { path = "../tonic-web" }
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
prost = "0.6.1"
hyper = "0.13.7"
