[package]
name = "example-hyper-warp"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "hyper-warp-server"
path = "src/server.rs"

[[bin]]
name = "hyper-warp-client"
path = "src/client.rs"

[[bin]]
name = "hyper-warp-server-multiplex"
path = "src/server_multiplex.rs"

[[bin]]
name = "hyper-warp-client-multiplex"
path = "src/client_multiplex.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
tonic = { path = "../../tonic" }
futures = { version = "0.3", default-features = false }
tower = "0.4"
hyper = "0.14"
http = "0.2"
http-body = "0.4.2"
warp = "0.3"

[build-dependencies]
tonic-build = { path = "../../tonic-build" }
