name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [beta]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Check all
      run: cargo check --all
    - name: Check with no default features
      run: cargo check -p tonic --no-default-features
    - name: Check with transport no tls
      run: cargo check -p tonic
    - name: Check with transport w/ openssl
      run: cargo check -p tonic --features openssl
    - name: Check with transport w/ rustls
      run: cargo check -p tonic --features rustls
    - name: Run tests
      run: cargo test --all --all-features
